### ISSUE TITLE
integrate the new look and feel (branding)

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#41] opened 2017-01-04 03:39 UTC
- [x] Sidebar empty state (faded logo?) OR no sidebar if not being used?

**Comment by keithamoss** [comment] 2017-04-15 12:00
Dupe of #41

**Comment by keithamoss** [comment] 2017-04-25 01:44
We've used a few random colours in the development so far. Since we've decided on purple as the primary colour via the logo let's create a proper theme for EALGIS that adheres to the material design spec and guidance.

[Material Design: Style & Colour](https://material.io/guidelines/style/color.html)
[Google's Material Colour Tool](https://material.io/color/)
[Third Party Material Palette Creator](https://www.materialpalette.com/)

Material-UI supports [custom themes](http://www.material-ui.com/#/customization/themes).

**Comment by keithamoss** [comment] 2017-07-05 12:43
- [ ] Point all relevant uses of `/styles/colors` at muiTheme
- [ ] Base64 inline move to dev deps
- [ ] Make logo SVG
- [ ] OL colours

**Closed** 2017-07-06 14:59 UTC
Labels: Experience: Design, Improvements: Enhancement
